<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211126143509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artiste (id INT AUTO_INCREMENT NOT NULL, edition_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, spotify VARCHAR(255) DEFAULT NULL, deezer VARCHAR(255) DEFAULT NULL, annee VARCHAR(255) DEFAULT NULL, origine LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', nom_spectacle_soiree VARCHAR(255) DEFAULT NULL, date LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', lang_code LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', is_receiving_quest TINYINT(1) NOT NULL, is_ilomember TINYINT(1) NOT NULL, label_sp VARCHAR(255) NOT NULL, label_en VARCHAR(255) NOT NULL, onu_code VARCHAR(255) NOT NULL, INDEX IDX_9C07354F74281A5E (edition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, debut DATE NOT NULL, fin DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_lieu (event_id INT NOT NULL, lieu_id INT NOT NULL, INDEX IDX_309C31F271F7E88B (event_id), INDEX IDX_309C31F26AB213CC (lieu_id), PRIMARY KEY(event_id, lieu_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_artiste (event_id INT NOT NULL, artiste_id INT NOT NULL, INDEX IDX_19509CE071F7E88B (event_id), INDEX IDX_19509CE021D25844 (artiste_id), PRIMARY KEY(event_id, artiste_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lieu (id INT AUTO_INCREMENT NOT NULL, adresse VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lieu_user (lieu_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_70F73F16AB213CC (lieu_id), INDEX IDX_70F73F1A76ED395 (user_id), PRIMARY KEY(lieu_id, user_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, lieu_id INT DEFAULT NULL, text VARCHAR(255) NOT NULL, date DATE NOT NULL, INDEX IDX_BF5476CA6AB213CC (lieu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_artiste (notification_id INT NOT NULL, artiste_id INT NOT NULL, INDEX IDX_8919BFF8EF1A9D84 (notification_id), INDEX IDX_8919BFF821D25844 (artiste_id), PRIMARY KEY(notification_id, artiste_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE artiste ADD CONSTRAINT FK_9C07354F74281A5E FOREIGN KEY (edition_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event_lieu ADD CONSTRAINT FK_309C31F271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_lieu ADD CONSTRAINT FK_309C31F26AB213CC FOREIGN KEY (lieu_id) REFERENCES lieu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_artiste ADD CONSTRAINT FK_19509CE071F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_artiste ADD CONSTRAINT FK_19509CE021D25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lieu_user ADD CONSTRAINT FK_70F73F16AB213CC FOREIGN KEY (lieu_id) REFERENCES lieu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lieu_user ADD CONSTRAINT FK_70F73F1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA6AB213CC FOREIGN KEY (lieu_id) REFERENCES lieu (id)');
        $this->addSql('ALTER TABLE notification_artiste ADD CONSTRAINT FK_8919BFF8EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_artiste ADD CONSTRAINT FK_8919BFF821D25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE');
            }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_artiste DROP FOREIGN KEY FK_19509CE021D25844');
        $this->addSql('ALTER TABLE notification_artiste DROP FOREIGN KEY FK_8919BFF821D25844');
        $this->addSql('ALTER TABLE artiste DROP FOREIGN KEY FK_9C07354F74281A5E');
        $this->addSql('ALTER TABLE event_lieu DROP FOREIGN KEY FK_309C31F271F7E88B');
        $this->addSql('ALTER TABLE event_artiste DROP FOREIGN KEY FK_19509CE071F7E88B');
        $this->addSql('ALTER TABLE event_lieu DROP FOREIGN KEY FK_309C31F26AB213CC');
        $this->addSql('ALTER TABLE lieu_user DROP FOREIGN KEY FK_70F73F16AB213CC');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA6AB213CC');
        $this->addSql('ALTER TABLE notification_artiste DROP FOREIGN KEY FK_8919BFF8EF1A9D84');
        $this->addSql('ALTER TABLE lieu_user DROP FOREIGN KEY FK_70F73F1A76ED395');
        $this->addSql('DROP TABLE artiste');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_lieu');
        $this->addSql('DROP TABLE event_artiste');
        $this->addSql('DROP TABLE lieu');
        $this->addSql('DROP TABLE lieu_user');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_artiste');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('ALTER TABLE artists MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE artists DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE artists ADD ARTISTES VARCHAR(39) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_PAYS1 VARCHAR(51) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_PAYS2 VARCHAR(32) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_PAYS3 VARCHAR(6) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_PAYS4 VARCHAR(11) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_VILLE1 VARCHAR(29) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_VILLE2 VARCHAR(12) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_VILLE3 VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ORIGINE_VILLE4 VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ANNEE DOUBLE PRECISION DEFAULT NULL, ADD EDITION VARCHAR(43) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD NOM SPECTACLE OU SOIREE VARCHAR(35) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD SPOTIFY VARCHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD DEEZER DOUBLE PRECISION DEFAULT NULL, ADD 1ER PROJET ATM VARCHAR(35) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 1ERE DATE VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 1ERE DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 1ERE SALLE VARCHAR(39) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 1ERE VILLE VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 2EME PROJET VARCHAR(35) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 2EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 2EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 2EME SALLE VARCHAR(43) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 2EME VILLE VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 3EME PROJET VARCHAR(35) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 3EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 3EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 3EME SALLE VARCHAR(43) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 3EME VILLE VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 4EME PROJET VARCHAR(26) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 4EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 4EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 4EME SALLE VARCHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 4EME VILLE VARCHAR(7) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 5EME PROJET VARCHAR(35) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 5EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 5EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 5EME SALLE VARCHAR(29) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 5EME VILLE VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 6EME PROJET VARCHAR(17) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 6EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 6EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 6EME SALLE VARCHAR(29) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 6EME VILLE VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 7EME PROJET VARCHAR(17) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 7EME DATE VARCHAR(9) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD 7EME DATE TIMESTAMP DOUBLE PRECISION DEFAULT NULL, ADD 7EME SALLE VARCHAR(29) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD OFFICIAL LANG CODE VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ISO2 CODE VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ISO3 CODE VARCHAR(3) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD geo_point_2d VARCHAR(29) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD IS RECEIVING QUEST VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD LABEL SP VARCHAR(20) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD IS ILOMEMBER VARCHAR(1) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD LABEL EN VARCHAR(18) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, ADD ONU CODE DOUBLE PRECISION DEFAULT NULL, CHANGE id id INT DEFAULT NULL');
    }
}
